// BCGA FCU PRO — web_ui.h
// Single-page dashboard served on GET /. Stored in PROGMEM as raw string.
//
// Generated by tools/build_web_ui.py — DO NOT EDIT BY HAND.
// Edit firmware/web_ui_dev/{style.css, app.js, index_pro.html} and rebuild.
//
// Section order:
//   - Header: gear logo, name, S8PA/D8PA tag, battery chip, BR/EN (default EN)
//   - Slot picker: 3 buttons at the top (always clickable)
//   - Engine (slot name + Single/Dual radio cards)
//   - Timings (DN/DR/DP em ms) + ROF max + ROF teórico
//   - Seletor (Pos1/Pos2; toggle 3-pos auto-ativa Hall e revela Pos3)
//   - Funções (Sw/Hall do gatilho, swap MOS, silent — invertTrig hidden)
//   - Sensibilidade (só Hall trigger): captura de ponto único
//   - Calibração do gatilho (só Hall trigger): ruído + solto/pressionado
//   - Calibração do seletor (só Hall sel): ruído + 3 posições
//   - Avançado (IS/IP anti-stiction + DB em 0,1 ms + Semi Max ROF)
//   - Diagnóstico (buzzer + Test MOS — 2s, respeita mosfetSwap)
//   - WiFi (trocar senha)
// Toolbar: Resetar slot · Recarregar · Salvar.
// Footer: link bcgaairsoft.com.br + versão + variante.

#pragma once

#include <Arduino.h>

const char WEB_UI_HTML[] PROGMEM = R"HTML(<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover" />
<title>BCGA FCU PRO</title>
<style>
/* BCGA FCU — shared web UI stylesheet (STR + PRO).
   Brutalism dark, mirrors /fcu/tour at bcgaairsoft.com.
   Yellow (#FCCD01) is the primary CTA/active color across both variants.
   The variant accent (verde STR / cyan PRO) is kept ONLY in the header
   border-bottom and SVG logo; everywhere else uses the BCGA yellow.
   No border-radius, sharp shadows, system condensed font stack. */

:root{
  --ink-900:#0A0A0A; --ink-700:#2E2E2E; --ink-500:#5C5C5C;
  --papel-100:#F5F2EB;
  --alert-500:#FCCD01; --alert-600:#E6B800;
  --line:rgba(245,242,235,.20);
  --line-soft:rgba(245,242,235,.15);
  --mute:rgba(245,242,235,.70);
  --mute-2:rgba(245,242,235,.50);
  --err:#E63600; --ok:#7BB67A;
  --accent:#8aab47; --accent-fg:#0A0A0A;  /* STR verde, secundário */
  --font-display:'Impact','Haettenschweiler','Arial Narrow Bold','Oswald',sans-serif;
  --font-mono:ui-monospace,'SF Mono',Menlo,Consolas,'Liberation Mono',monospace;
}
body.variant-pro{ --accent:#00bcd4; }

*{box-sizing:border-box}
*::before,*::after{box-sizing:border-box}

html,body{
  margin:0;padding:0;
  background:var(--ink-900);color:var(--papel-100);
  font:15px/1.45 var(--font-mono);
  -webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale;
}

/* ─── Header ──────────────────────────────────────────────────────── */
header{
  position:sticky;top:0;z-index:5;
  background:var(--ink-900);
  border-bottom:2px solid var(--accent);
  padding:10px 14px;
  display:flex;align-items:center;gap:10px;flex-wrap:wrap;
}
header .brand{display:flex;align-items:center;gap:10px;flex:1;min-width:0}
header .brand svg{flex:0 0 auto}
header .brand .txt{display:flex;flex-direction:column;line-height:1.1;min-width:0}
header .brand .name{
  font-family:var(--font-display);text-transform:uppercase;
  font-size:16px;color:var(--papel-100);letter-spacing:.5px;
}
header .brand .sub{
  font-size:12px;color:var(--mute-2);
  font-family:var(--font-mono);
}
.lang{display:flex;gap:6px}
.lang button{
  background:var(--ink-700);
  border:2px solid var(--line);
  color:var(--mute);
  padding:4px 10px;
  cursor:pointer;font:inherit;
  font-family:var(--font-display);text-transform:uppercase;
  font-size:13px;letter-spacing:.5px;
}
.lang button.on{
  background:var(--alert-500);color:var(--ink-900);
  border-color:var(--alert-500);
}

/* Battery chip (only present on PRO HTML) */
.battChip{
  display:inline-flex;align-items:center;gap:6px;
  padding:4px 10px;
  background:var(--ink-700);
  border:2px solid var(--line);
  color:var(--mute);
  font-family:var(--font-mono);
  font-size:13px;font-weight:700;
}
.battChip.ok{color:var(--ok);border-color:var(--ok)}
.battChip.warn{color:var(--alert-500);border-color:var(--alert-500)}
.battChip.err{color:var(--err);border-color:var(--err)}
.battChip.cut{text-decoration:line-through;opacity:.6}

/* ─── Main layout ─────────────────────────────────────────────────── */
main{padding:14px;max-width:760px;margin:0 auto;padding-bottom:110px}

.slotPick{display:flex;gap:8px;justify-content:center;margin:0 0 12px}
.slot-btn{
  flex:0 0 auto;
  width:60px;height:48px;
  background:var(--ink-700);
  border:2px solid var(--line);
  color:var(--mute);
  font-family:var(--font-display);text-transform:uppercase;
  font-weight:400;font-size:22px;
  cursor:pointer;
  letter-spacing:.5px;
}
.slot-btn.on{
  background:var(--alert-500);color:var(--ink-900);
  border-color:var(--alert-500);
}

/* ─── Section card ────────────────────────────────────────────────── */
section{
  background:var(--ink-700);
  border:2px solid var(--line);
  padding:12px 14px 10px;
  margin-bottom:12px;
}
section h2{
  margin:0 0 12px;
  padding-bottom:8px;
  border-bottom:1px solid var(--line-soft);
  font-family:var(--font-display);text-transform:uppercase;
  font-size:17px;letter-spacing:1px;
  color:var(--papel-100);
  display:flex;align-items:center;gap:8px;
}

/* ─── Row / control grid ──────────────────────────────────────────── */
.row{display:flex;align-items:center;gap:10px;margin:8px 0;flex-wrap:wrap}
.row label{
  flex:1;min-width:120px;
  font-family:var(--font-display);text-transform:uppercase;
  font-size:13px;letter-spacing:.5px;
  color:var(--mute);
  display:flex;align-items:center;gap:6px;
}
.row .ctrl{
  flex:2;min-width:160px;
  display:flex;align-items:center;gap:8px;
}

/* ─── Form controls ───────────────────────────────────────────────── */
input[type=text],input[type=number],input[type=password],select{
  background:var(--ink-900);color:var(--papel-100);
  border:2px solid var(--line);
  padding:8px 10px;font:inherit;
  font-family:var(--font-mono);
  width:100%;outline:none;
}
input[type=text]:focus,input[type=number]:focus,input[type=password]:focus,select:focus{
  border-color:var(--alert-500);
}
select{
  -webkit-appearance:none;appearance:none;
  background-image:url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 10 6'><path d='M0 0l5 6 5-6z' fill='%23F5F2EB'/></svg>");
  background-repeat:no-repeat;
  background-position:right 12px center;
  background-size:10px 6px;
  padding-right:30px;
}

/* Slider: flat track, square thumb */
input[type=range]{
  -webkit-appearance:none;appearance:none;
  width:100%;height:6px;background:transparent;
  padding:0;margin:0;outline:none;cursor:pointer;border:none;
}
input[type=range]::-webkit-slider-runnable-track{
  height:6px;background:var(--ink-900);border:1px solid var(--line);
}
input[type=range]::-webkit-slider-thumb{
  -webkit-appearance:none;
  width:14px;height:14px;
  background:var(--alert-500);
  border:1px solid var(--papel-100);
  margin-top:-5px;cursor:pointer;
}
input[type=range]::-moz-range-track{
  height:6px;background:var(--ink-900);border:1px solid var(--line);
}
input[type=range]::-moz-range-thumb{
  width:14px;height:14px;
  background:var(--alert-500);
  border:1px solid var(--papel-100);
  border-radius:0;cursor:pointer;
}

/* Toggle: rectangular pill */
.toggle{
  display:inline-flex;align-items:center;gap:8px;
  cursor:pointer;
  color:var(--mute-2);font-size:13px;
  font-family:var(--font-mono);
}
.toggle input[type=checkbox]{
  appearance:none;-webkit-appearance:none;
  width:32px;height:16px;
  background:var(--ink-900);
  border:2px solid var(--line);
  position:relative;cursor:pointer;flex:0 0 auto;
  padding:0;margin:0;
  transition:background .1s linear, border-color .1s linear;
}
.toggle input[type=checkbox]::before{
  content:'';
  position:absolute;top:1px;left:1px;
  width:10px;height:10px;
  background:var(--papel-100);
  transition:transform .1s linear, background .1s linear;
}
.toggle input[type=checkbox]:checked{
  background:var(--alert-500);border-color:var(--alert-500);
}
.toggle input[type=checkbox]:checked::before{
  transform:translateX(16px);background:var(--ink-900);
}

/* ─── Buttons ─────────────────────────────────────────────────────── */
.btn{
  background:var(--alert-500);color:var(--ink-900);
  border:2px solid var(--alert-500);
  padding:9px 16px;
  font:inherit;
  font-family:var(--font-display);text-transform:uppercase;
  font-size:14px;letter-spacing:.5px;
  cursor:pointer;
  box-shadow:4px 4px 0 var(--papel-100);
  transition:transform .1s linear, box-shadow .1s linear, background .1s linear;
}
.btn:hover{
  background:var(--alert-600);
  transform:translate(-2px,-2px);
  box-shadow:6px 6px 0 var(--papel-100);
}
.btn:active{
  transform:translate(2px,2px);
  box-shadow:2px 2px 0 var(--papel-100);
}
.btn.ghost{
  background:transparent;color:var(--papel-100);
  border-color:var(--papel-100);
  box-shadow:4px 4px 0 var(--ink-900);
}
.btn.ghost:hover{
  background:var(--papel-100);color:var(--ink-900);
  box-shadow:6px 6px 0 var(--ink-900);
}
.btn.danger{
  background:var(--err);color:var(--papel-100);
  border-color:var(--err);
  box-shadow:4px 4px 0 var(--papel-100);
}
.btn.danger:hover{
  background:#cc2e00;
  box-shadow:6px 6px 0 var(--papel-100);
}
.btn.warn{
  background:transparent;color:var(--err);
  border-color:var(--err);
  box-shadow:4px 4px 0 var(--ink-900);
}
.btn.warn:hover{
  background:var(--err);color:var(--papel-100);
  box-shadow:6px 6px 0 var(--ink-900);
}
.btn.sm{
  padding:6px 12px;font-size:13px;
  box-shadow:3px 3px 0 var(--papel-100);
}
.btn.sm:hover{box-shadow:5px 5px 0 var(--papel-100)}
.btn.sm.ghost{box-shadow:3px 3px 0 var(--ink-900)}
.btn.sm.ghost:hover{box-shadow:5px 5px 0 var(--ink-900)}
.btn.sm.warn{box-shadow:3px 3px 0 var(--ink-900)}
.btn.sm.warn:hover{box-shadow:5px 5px 0 var(--ink-900)}

/* ─── Slider+number pair, stepper ─────────────────────────────────── */
.pair{display:grid;grid-template-columns:1fr 80px;gap:8px;align-items:center}
.stepper{display:flex;align-items:center;gap:8px;width:100%}
.stepper .btn{
  flex:0 0 auto;min-width:40px;padding:6px 0;
  font-size:18px;line-height:1;
  box-shadow:none;
}
.stepper .btn:hover{transform:none;box-shadow:none;background:var(--papel-100);color:var(--ink-900)}
.stepper .btn:active{transform:none;box-shadow:none}
.stepper .stepper-val{
  flex:1;text-align:center;
  font-family:var(--font-mono);font-weight:700;
  color:var(--papel-100);
  font-variant-numeric:tabular-nums;min-width:0;
}
.stepper .stepper-val.off{color:var(--mute-2);font-weight:400}

/* ─── Stats grid + lube + battery ─────────────────────────────────── */
.stat-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}
@media(min-width:540px){.stat-grid{grid-template-columns:repeat(4,1fr)}}
.stat{
  background:var(--ink-900);
  border:2px solid var(--line);
  padding:8px 10px;min-width:0;
}
.stat-label{
  font-family:var(--font-display);text-transform:uppercase;
  font-size:11px;letter-spacing:.5px;
  color:var(--mute-2);line-height:1;
}
.stat-value{
  font-family:var(--font-mono);
  font-size:20px;font-weight:700;
  color:var(--alert-500);
  font-variant-numeric:tabular-nums;
  margin-top:4px;
  overflow:hidden;text-overflow:ellipsis;white-space:nowrap;
}
.stat.lube .stat-value{font-size:14px;font-weight:400;color:var(--papel-100)}
.lube-bar{
  height:6px;background:rgba(245,242,235,.10);
  margin:4px 0;
}
.lube-fill{
  height:100%;background:var(--alert-500);
  transition:width 0.3s, background-color 0.3s;
  width:0;
}
.lube-fill.warn{background:var(--alert-600)}
.lube-fill.due{background:var(--err)}
.lube-txt{
  font-size:12px;color:var(--mute-2);
  font-variant-numeric:tabular-nums;
  font-family:var(--font-mono);
}
.stat.batt .stat-value.ok{color:var(--ok)}
.stat.batt .stat-value.warn{color:var(--alert-500)}
.stat.batt .stat-value.err{color:var(--err)}
.stat.batt .stat-value.cut{color:var(--err);text-decoration:line-through}

/* ─── Radio cards (Engine) ────────────────────────────────────────── */
.radio-row{display:grid;grid-template-columns:1fr;gap:8px}
@media(min-width:480px){.radio-row{grid-template-columns:1fr 1fr}}
.radio-card{
  background:var(--ink-900);
  border:2px solid var(--line);
  padding:12px;cursor:pointer;text-align:center;
  font-family:var(--font-display);text-transform:uppercase;
  font-size:14px;letter-spacing:.5px;
  color:var(--mute);
  opacity:.7;
}
.radio-card.on{
  border-color:var(--alert-500);
  background:rgba(252,205,1,.08);
  color:var(--papel-100);
  opacity:1;
}
.radio-card .small{
  display:block;
  font-family:var(--font-mono);text-transform:none;letter-spacing:0;
  font-size:12px;color:var(--mute-2);margin-top:5px;
}

/* ─── Toolbar (sticky bottom) ─────────────────────────────────────── */
.toolbar{
  position:fixed;left:0;right:0;bottom:0;
  padding:10px 14px;
  background:var(--ink-900);
  border-top:2px solid var(--line);
  display:flex;gap:10px;
  justify-content:space-between;align-items:center;
  z-index:4;flex-wrap:wrap;
}
.toolbar .grp{display:flex;gap:10px}

/* ─── Toast ───────────────────────────────────────────────────────── */
.toast{
  position:fixed;left:50%;bottom:90px;
  transform:translateX(-50%);
  background:var(--alert-500);color:var(--ink-900);
  padding:9px 16px;
  font-family:var(--font-display);text-transform:uppercase;
  font-size:14px;letter-spacing:.5px;
  opacity:0;transition:opacity .25s;
  pointer-events:none;z-index:10;max-width:90%;
  border:2px solid var(--ink-900);
  box-shadow:4px 4px 0 var(--papel-100);
}
.toast.show{opacity:1}
.toast.err{background:var(--err);color:var(--papel-100);border-color:var(--papel-100)}

/* ─── Theoretical ROF chip ────────────────────────────────────────── */
.rofTheoBox{
  display:flex;align-items:center;justify-content:space-between;
  padding:10px 12px;
  background:var(--ink-900);
  border:2px solid var(--line);
  margin:6px 0 0;
  font-family:var(--font-display);text-transform:uppercase;
  font-size:13px;letter-spacing:.5px;
  color:var(--mute);
}
.rofTheoBox .v{
  font-family:var(--font-mono);font-weight:700;
  color:var(--alert-500);text-transform:none;
  font-variant-numeric:tabular-nums;letter-spacing:0;
}

/* ─── Misc ────────────────────────────────────────────────────────── */
.muted{color:var(--mute-2);font-size:13px;font-family:var(--font-mono)}
.divider{height:1px;background:var(--line);margin:10px 0}
.hide{display:none!important}

/* Help (?) button + popover */
.help{
  display:inline-flex;align-items:center;justify-content:center;
  width:20px;height:20px;
  background:var(--ink-900);
  border:1px solid var(--line);
  color:var(--mute);
  font-size:12px;font-weight:700;
  cursor:pointer;padding:0;font:inherit;
}
.help:hover{
  background:var(--alert-500);color:var(--ink-900);
  border-color:var(--alert-500);
}
.popover{
  position:absolute;
  background:var(--ink-900);
  border:2px solid var(--alert-500);
  padding:10px 12px;
  font-size:13px;color:var(--papel-100);
  max-width:280px;z-index:30;
  box-shadow:4px 4px 0 var(--papel-100);
  font-family:var(--font-mono);line-height:1.4;
}

/* Overlay (lock, calibration) */
.overlay{
  position:fixed;inset:0;
  background:rgba(0,0,0,.85);
  display:flex;align-items:center;justify-content:center;
  z-index:20;padding:14px;
}
.overlay .box{
  background:var(--ink-900);
  border:2px solid var(--papel-100);
  padding:18px;max-width:420px;width:100%;
  box-shadow:6px 6px 0 var(--papel-100);
}
.overlay h3{
  margin:0 0 10px;
  font-family:var(--font-display);text-transform:uppercase;
  font-size:19px;letter-spacing:1px;
  color:var(--alert-500);
}

/* Live ADC readout */
.live{
  font-family:var(--font-display);
  font-size:48px;font-weight:400;letter-spacing:1px;
  text-align:center;margin:14px 0;
  color:var(--alert-500);
  font-variant-numeric:tabular-nums;line-height:1;
}
.live .lbl{
  display:block;
  font-family:var(--font-display);text-transform:uppercase;
  font-size:11px;letter-spacing:1px;
  color:var(--mute-2);font-weight:400;
}

/* Step dots (square) */
.steps{display:flex;gap:6px;justify-content:center;margin:8px 0 12px}
.dot{width:8px;height:8px;background:var(--line)}
.dot.on{background:var(--alert-500)}

/* Trigger test dot (square) */
.trigDot{
  display:inline-block;
  width:12px;height:12px;
  background:var(--ink-900);
  border:1px solid var(--mute);
  transition:background .08s, border-color .08s;
}
.trigDot.on{
  background:var(--alert-500);
  border-color:var(--alert-500);
}

/* Footer */
footer{
  padding:18px 12px 24px;
  text-align:center;
  color:var(--mute-2);font-size:12px;
  font-family:var(--font-mono);
}
footer a{color:var(--alert-500);text-decoration:none}
footer a:hover{text-decoration:underline}
</style></head>
<body class="variant-pro">

<header>
  <div class="brand">
    <svg width="32" height="32" viewBox="0 0 64 64" aria-hidden="true">
      <path fill="#00bcd4" fill-rule="evenodd" d="M28 2 L36 2 L37 9 L43 11 L48 6 L54 12 L49 17 L51 23 L58 24 L58 32 L51 33 L49 39 L54 44 L48 50 L43 45 L37 47 L36 54 L28 54 L27 47 L21 45 L16 50 L10 44 L15 39 L13 33 L6 32 L6 24 L13 23 L15 17 L10 12 L16 6 L21 11 L27 9 Z M32 18 a10 10 0 1 0 0.01 0 Z"/>
    </svg>
    <div class="txt">
      <div class="name" id="hdrName">BCGA FCU</div>
      <div class="sub" id="hdrSub">· · ·</div>
    </div>
  </div>
  <div id="battChip" class="battChip hide"><span id="battTxt">—</span></div>
  <div class="lang">
    <button id="langBR" type="button">BR</button>
    <button id="langEN" class="on" type="button">EN</button>
  </div>
</header>

<main>

  <div class="slotPick" id="slotPick"></div>

  <!-- Statistics ======================================================== -->
  <section>
    <h2><span data-i="statsSec">Statistics</span></h2>
    <div class="stat-grid">
      <div class="stat batt" id="statBatt">
        <div class="stat-label" data-i="statBattLbl">Battery</div>
        <div class="stat-value" id="statBattVal">—</div>
      </div>
      <div class="stat">
        <div class="stat-label" data-i="statShotsSession">Session shots</div>
        <div class="stat-value" id="statShotsSessionVal">—</div>
      </div>
      <div class="stat">
        <div class="stat-label" data-i="statShotsTotal">Total shots</div>
        <div class="stat-value" id="statShotsTotalVal">—</div>
      </div>
      <div class="stat lube">
        <div class="stat-label" data-i="statLube">Next lubrication</div>
        <div class="lube-bar"><div class="lube-fill" id="lubeFill"></div></div>
        <div class="lube-txt" id="lubeTxt">— / 10 000</div>
      </div>
    </div>
  </section>

  <!-- Engine ============================================================ -->
  <section>
    <h2><span data-i="solSec">Engine</span></h2>
    <div class="row">
      <label data-i="slotName">Slot name</label>
      <div class="ctrl"><input type="text" id="slotName" maxlength="15" /></div>
    </div>
    <div class="radio-row">
      <div class="radio-card" id="solS">
        <div data-i="solSHead">Single Solenoid S8PA</div>
        <span class="small" data-i="solS">1 solenoid (Jack, Backdraft)</span>
      </div>
      <div class="radio-card" id="solD">
        <div data-i="solDHead">Dual Solenoid D8PA</div>
        <span class="small" data-i="solD">2 solenoids (F2, Pulsar)</span>
      </div>
    </div>
  </section>

  <!-- Timings =========================================================== -->
  <section>
    <h2><span data-i="timSec">Timings</span></h2>
    <div class="row" id="rowDn">
      <label>DN <button class="help" data-h="dn" type="button">?</button></label>
      <div class="ctrl"><div class="pair" style="width:100%"><input type="range" id="dnR" min="2" max="80" /><input type="number" id="dnN" min="2" max="80" /></div></div>
    </div>
    <div class="row" id="rowDr">
      <label>DR <button class="help" data-h="dr" type="button">?</button></label>
      <div class="ctrl"><div class="pair" style="width:100%"><input type="range" id="drR" min="2" max="80" /><input type="number" id="drN" min="2" max="80" /></div></div>
    </div>
    <div class="row" id="rowDp">
      <label>DP <button class="help" data-h="dp" type="button">?</button></label>
      <div class="ctrl"><div class="pair" style="width:100%"><input type="range" id="dpR" min="2" max="80" /><input type="number" id="dpN" min="2" max="80" /></div></div>
    </div>
    <div class="row">
      <label data-i="rofLbl">ROF max (rps) <button class="help" data-h="rof" type="button">?</button></label>
      <div class="ctrl"><input type="number" id="rofN" min="0" max="50" /></div>
    </div>
    <div class="rofTheoBox">
      <span data-i="rofTheoLbl">Theoretical ROF <button class="help" data-h="rofTheo" type="button">?</button></span>
      <span class="v" id="rofTheoVal">— rps</span>
    </div>
  </section>

  <!-- Selector ========================================================== -->
  <section>
    <h2><span data-i="selSec">Selector</span></h2>
    <div class="row"><label data-i="selIn">Selector input <button class="help" data-h="selMode" type="button">?</button></label><div class="ctrl"><select id="selMode"><option value="0" data-i="sw">Microswitch</option><option value="1" data-i="hl">Hall (analog)</option></select></div></div>
    <div class="row"><label data-i="pos1">Position 1 <button class="help" data-h="pos" type="button">?</button></label><div class="ctrl"><select id="selPos1"></select></div></div>
    <div class="row"><label data-i="pos2">Position 2 <button class="help" data-h="pos" type="button">?</button></label><div class="ctrl"><select id="selPos2"></select></div></div>
    <div class="row">
      <label data-i="sel3">3-position selector <button class="help" data-h="sel3" type="button">?</button></label>
      <div class="ctrl"><label class="toggle"><input type="checkbox" id="sel3pos" /> <span data-i="sel3H">enable Pos 3 (auto-Hall)</span></label></div>
    </div>
    <div class="row" id="rowPos3"><label data-i="pos3">Position 3</label><div class="ctrl"><select id="selPos3"></select></div></div>
  </section>

  <!-- Functions ========================================================= -->
  <section>
    <h2><span data-i="funcSec">Functions</span></h2>
    <div class="row"><label data-i="trigIn">Trigger <button class="help" data-h="trigMode" type="button">?</button></label><div class="ctrl"><select id="trigMode"><option value="0" data-i="sw">Microswitch</option><option value="1" data-i="hl">Hall (analog)</option></select></div></div>
    <div class="row hide" id="rowInvert"><label data-i="invTrig">Invert trigger</label><div class="ctrl"><label class="toggle"><input type="checkbox" id="invertTrig" /></label></div></div>
    <div class="row" id="rowMosSwap"><label data-i="mosSwap">Swap MOS 1 ↔ 2 <button class="help" data-h="mosSwap" type="button">?</button></label><div class="ctrl"><label class="toggle"><input type="checkbox" id="mosfetSwap" /> <span data-i="mosSwapH">fix swapped wiring</span></label></div></div>
    <div class="row"><label data-i="silent">Silent mode <button class="help" data-h="silent" type="button">?</button></label><div class="ctrl"><label class="toggle"><input type="checkbox" id="silent" /> <span data-i="silentH">skip buzzer while in use</span></label></div></div>
  </section>

  <!-- Hall sensitivity & calibration (auto-show) ========================= -->
  <section id="secSens" class="hide">
    <h2><span data-i="sensSec">Trigger sensitivity</span> <button class="help" data-h="sens" type="button">?</button></h2>
    <div class="muted" data-i="sensHelp">Pull trigger to the desired fire point and click Save.</div>
    <div class="live"><span class="lbl" data-i="liveAdc">ADC reading</span><span id="sensLive">0</span></div>
    <div class="row">
      <label data-i="curPoint">Current point</label>
      <div class="ctrl"><span class="muted" id="curPoint">—</span></div>
    </div>
    <div class="row">
      <div></div>
      <div class="ctrl"><button class="btn" id="sensSaveBtn" type="button" data-i="savePoint">Save point</button></div>
    </div>
  </section>

  <section id="secCalTrig" class="hide">
    <h2><span data-i="calTrigSec">Trigger calibration</span></h2>
    <div class="muted" data-i="calTrigHelp">Start with noise (fires 1 test cycle). Don't pull the trigger.</div>
    <div class="row" style="margin-top:10px">
      <label data-i="calNoise">Noise <button class="help" data-h="noise" type="button">?</button></label>
      <div class="ctrl"><button class="btn ghost sm" id="calTrigNoiseBtn" type="button" data-i="calBtn">Calibrate</button>
      <span class="muted" id="calTrigNoiseVals">±—</span></div>
    </div>
    <div class="row">
      <label data-i="calTrig">Trigger <button class="help" data-h="cal" type="button">?</button></label>
      <div class="ctrl"><button class="btn ghost sm" id="calTrigBtn" type="button" data-i="calBtn">Calibrate</button>
      <span class="muted" id="calTrigVals">low=— high=—</span></div>
    </div>
  </section>

  <section id="secCalSel" class="hide">
    <h2><span data-i="calSelSec">Selector calibration</span></h2>
    <div class="muted" data-i="calSelHelp">Start with noise (fires 1 test cycle). Don't touch the selector.</div>
    <div class="row" style="margin-top:10px">
      <label data-i="calNoise">Noise <button class="help" data-h="noise" type="button">?</button></label>
      <div class="ctrl"><button class="btn ghost sm" id="calSelNoiseBtn" type="button" data-i="calBtn">Calibrate</button>
      <span class="muted" id="calSelNoiseVals">±—</span></div>
    </div>
    <div class="row">
      <label data-i="calSel">Selector (3 pos) <button class="help" data-h="cal" type="button">?</button></label>
      <div class="ctrl"><button class="btn ghost sm" id="calSelBtn" type="button" data-i="calBtn">Calibrate</button>
      <span class="muted" id="calSelVals">—</span></div>
    </div>
  </section>

  <!-- Advanced ========================================================== -->
  <section>
    <h2><span data-i="advSec">Advanced</span></h2>
    <div class="row">
      <label>IS <button class="help" data-h="is" type="button">?</button></label>
      <div class="ctrl"><div class="stepper">
        <button class="btn ghost" data-step="is" data-dir="-1" type="button">−</button>
        <span class="stepper-val" id="isVal">— s</span>
        <button class="btn ghost" data-step="is" data-dir="1" type="button">+</button>
      </div></div>
    </div>
    <div class="row">
      <label>IP <button class="help" data-h="ip" type="button">?</button></label>
      <div class="ctrl"><div class="stepper">
        <button class="btn ghost" data-step="ip" data-dir="-1" type="button">−</button>
        <span class="stepper-val" id="ipVal">— ms</span>
        <button class="btn ghost" data-step="ip" data-dir="1" type="button">+</button>
      </div></div>
    </div>
    <div class="row" id="rowDb">
      <label>DB <button class="help" data-h="db" type="button">?</button></label>
      <div class="ctrl"><div class="pair" style="width:100%"><input type="range" id="dbR" min="5" max="150" /><input type="number" id="dbN" min="5" max="150" /></div></div>
    </div>
    <div class="row">
      <label data-i="semiRof">Semi Max ROF (ms) <button class="help" data-h="semiRof" type="button">?</button></label>
      <div class="ctrl"><input type="number" id="semiRofN" min="0" max="500" /></div>
    </div>
    <div class="row">
      <label data-i="cfgLock">Config LOCK <button class="help" data-h="cfgLock" type="button">?</button></label>
      <div class="ctrl">
        <span class="muted" id="cfgLockStatus">—</span>
      </div>
    </div>
    <div class="row" id="rowCfgLockSet">
      <label data-i="cfgLockSetLbl">New password</label>
      <div class="ctrl">
        <input type="password" id="cfgLockPwd" minlength="4" maxlength="32" placeholder="****" />
        <button class="btn ghost sm" id="cfgLockSetBtn" type="button" data-i="cfgLockSet">Set</button>
      </div>
    </div>
    <div class="row hide" id="rowCfgLockManage">
      <div></div>
      <div class="ctrl">
        <button class="btn warn sm" id="cfgLockLockBtn" type="button" data-i="cfgLockLock">Lock now</button>
        <button class="btn ghost sm" id="cfgLockClearBtn" type="button" data-i="cfgLockClear">Clear password</button>
      </div>
    </div>
  </section>

  <!-- Diagnostics ======================================================= -->
  <section>
    <h2><span data-i="diagSec">Diagnostics</span></h2>
    <div class="row">
      <label data-i="buzz">Buzzer <button class="help" data-h="buzz" type="button">?</button></label>
      <div class="ctrl">
        <select id="buzzPick">
          <option value="1">Boot</option>
          <option value="2" data-i="bzMode">Mode change</option>
          <option value="3" data-i="bzSave">Save OK</option>
          <option value="4" data-i="bzWifi">WiFi ON</option>
          <option value="5" data-i="bzLow">Low battery</option>
          <option value="6" data-i="bzCut">Battery CUT</option>
          <option value="7" data-i="bzTest">Test</option>
        </select>
        <button class="btn sm" id="buzzPlay" type="button" data-i="play">Play</button>
      </div>
    </div>
    <div class="row">
      <label data-i="mosTest">MOSFET test (2s) <button class="help" data-h="mosTest" type="button">?</button></label>
      <div class="ctrl">
        <button class="btn danger sm" id="mos1Btn" type="button">SOL 1 (Poppet)</button>
        <button class="btn danger sm" id="mos2Btn" type="button">SOL 2 (Nozzle)</button>
      </div>
    </div>
    <div class="row">
      <label data-i="trigTest">Trigger test <button class="help" data-h="trigTest" type="button">?</button></label>
      <div class="ctrl">
        <button class="btn ghost sm" id="trigTestBtn" type="button" data-i="trigTestStart">Start</button>
        <span class="trigDot" id="trigTestDot"></span>
        <span class="muted" id="trigTestMsg" data-i="trigTestIdle">—</span>
      </div>
    </div>
  </section>

  <!-- WiFi ============================================================== -->
  <section>
    <h2><span data-i="wifiSec">WiFi</span></h2>
    <div class="row">
      <label data-i="newPwd">New password <button class="help" data-h="pwd" type="button">?</button></label>
      <div class="ctrl"><input type="password" id="wifiPwd" minlength="8" maxlength="32" placeholder="********" /></div>
    </div>
    <div class="row"><div></div><div class="ctrl"><button class="btn ghost" id="setPwdBtn" type="button" data-i="changePwd">Change password</button></div></div>
  </section>

</main>

<div class="toolbar">
  <button class="btn warn" id="btnReset" type="button" data-i="resetSlot">Reset slot</button>
  <div class="grp">
    <button class="btn ghost" id="btnReload" type="button" data-i="reload">Reload</button>
    <button class="btn" id="btnSave" type="button" data-i="save">Save slot</button>
  </div>
</div>

<footer>
  <a href="https://bcgaairsoft.com.br" target="_blank" rel="noopener">bcgaairsoft.com.br</a>
  &nbsp;•&nbsp; <span id="ftVer">v—</span>
  &nbsp;•&nbsp; <span id="ftVar">—</span>
</footer>

<div id="toast" class="toast">OK</div>

<div id="lockOver" class="overlay hide">
  <div class="box">
    <h3 data-i="lockTitle">Configuration locked</h3>
    <p class="muted" data-i="lockMsg">Enter the password to unlock the FCU configuration.</p>
    <div class="row" style="margin-top:10px">
      <label data-i="lockPwd">Password</label>
      <div class="ctrl"><input type="password" id="lockPwdInput" maxlength="32" placeholder="****" /></div>
    </div>
    <p class="muted" data-i="lockForgotHint" style="margin-top:8px">Forgot the password? Hold the WiFi button + trigger at boot for 30 s to factory-reset.</p>
    <div style="display:flex;gap:8px;justify-content:flex-end;flex-wrap:wrap;margin-top:8px">
      <button class="btn" id="lockUnlockBtn" type="button" data-i="lockUnlock">Unlock</button>
    </div>
  </div>
</div>

<div id="calOver" class="overlay hide">
  <div class="box">
    <h3 id="calTitle">Calibration</h3>
    <div class="steps"><div class="dot on" id="step1"></div><div class="dot" id="step2"></div><div class="dot" id="step3"></div></div>
    <div class="muted" id="calMsg">—</div>
    <div class="live"><span class="lbl" data-i="liveAdc">ADC reading</span><span id="liveVal">0</span></div>
    <div style="display:flex;gap:8px;justify-content:flex-end;flex-wrap:wrap">
      <button class="btn ghost" id="calCancel" type="button" data-i="cancel">Cancel</button>
      <button class="btn" id="calNext" type="button" data-i="capture">Capture</button>
    </div>
  </div>
</div>

<script>
"use strict";
const IS_PRO = document.body.classList.contains("variant-pro");

const I = {
  br:{
    slotName:"Nome do slot",
    solSec:"Engine",
    solSHead:"Single Solenoide S8PA",solDHead:"Dual Solenoide D8PA",
    solS:"1 solenoide (Jack, Backdraft)",solD:"2 solenoides (F2, Pulsar)",
    timSec:"Timings",rofLbl:"ROF máx (rps)",rofTheoLbl:"ROF teórico",semiRof:"Semi Max ROF (ms)",
    selSec:"Seletor",pos1:"Posição 1",pos2:"Posição 2",pos3:"Posição 3",
    sel3:"Seletor de 3 posições",sel3H:"habilitar Pos 3 (ativa Hall)",
    funcSec:"Funções",advSec:"Avançado",
    statsSec:"Estatísticas",statBattLbl:"Bateria",statShotsSession:"Tiros (sessão)",statShotsTotal:"Tiros (total)",statLube:"Próxima lubrificação",
    cfgLock:"Config LOCK",cfgLockOff:"OFF (sem senha)",cfgLockOnUnlocked:"ATIVO — destrancado",
    cfgLockSetLbl:"Nova senha",cfgLockSet:"Definir",cfgLockLock:"Trancar agora",cfgLockClear:"Remover senha",
    cfgLockTooShort:"Senha curta (mín. 4)",cfgLockOk:"Senha gravada",cfgLockCleared:"Senha removida",
    cfgLockUnlocked:"Destrancado",cfgLockBadPwd:"Senha incorreta",
    cfgLockClearConfirm:"Remover a senha do Config LOCK?",
    lockTitle:"Configuração trancada",lockMsg:"Digite a senha para destravar a configuração do FCU.",
    lockPwd:"Senha",lockUnlock:"Destrancar",
    lockForgotHint:"Esqueceu a senha? Segure o gatilho 30 s no boot para reset de fábrica.",
    trigIn:"Gatilho",selIn:"Tipo do seletor",sw:"Microswitch",hl:"Hall (analog)",
    invTrig:"Inverter gatilho",
    mosSwap:"Trocar MOS 1 ↔ 2",mosSwapH:"corrigir fiação trocada",
    silent:"Modo silencioso",silentH:"não tocar buzzer no uso",
    sensSec:"Sensibilidade do gatilho",sensHelp:"Puxe o gatilho até onde quer que dispare e clique em Salvar.",
    curPoint:"Ponto atual",savePoint:"Salvar ponto",liveAdc:"Leitura ADC",
    calTrigSec:"Calibração do gatilho",calTrigHelp:"Comece pelo ruído (faz 1 disparo de teste). Não puxe o gatilho.",
    calSelSec:"Calibração do seletor",calSelHelp:"Comece pelo ruído (faz 1 disparo de teste). Não toque no seletor.",
    calNoise:"Ruído",calTrig:"Gatilho",calSel:"Seletor (3 pos)",calBtn:"Calibrar",
    diagSec:"Diagnóstico",buzz:"Buzzer",bzMode:"Trocar modo",bzSave:"Salvar OK",bzWifi:"WiFi ON",bzLow:"Bateria baixa",bzCut:"Bateria CUT",bzTest:"Teste",play:"Tocar",mosTest:"Teste MOSFET (2s)",
    off:"off",
    trigTest:"Teste gatilho",trigTestStart:"Iniciar",trigTestStop:"Parar",trigTestIdle:"—",trigTestDone:"teste concluído",
    wifiSec:"WiFi",newPwd:"Nova senha",changePwd:"Trocar senha",
    reload:"Recarregar",save:"Salvar slot",resetSlot:"Resetar slot",cancel:"Cancelar",capture:"Capturar",saveCal:"Salvar",
    fSafe:"SAFE",fSemi:"SEMI",fFull:"FULL",fB2:"Burst 2",fB3:"Burst 3",fB4:"Burst 4",
    saved:"Slot salvo",saveFail:"Falha ao salvar",reloaded:"Recarregado",resetOk:"Slot resetado",
    resetConfirm:"Restaurar este slot para os valores padrão?",
    pwdOk:"Senha trocada",pwdBad:"Senha curta (mín. 8)",buzzed:"Buzzer ✓",
    mosOk:"MOSFET pulsando 2s",mosFail:"Não foi possível",
    pointSaved:"Ponto salvo: ADC ",
    noiseRunning:"Disparando ciclo de teste…",noiseOk:"Ruído capturado: ±",
    calStep1:"Solte completamente o gatilho e clique em Capturar.",
    calStep2:"Pressione o gatilho até o fim e clique em Capturar.",
    calStep3:"Valores capturados. Clique em Salvar para gravar.",
    calStepSel:"Mova o seletor para a posição",
    calRangeErr:"Curso insuficiente — repita.",
    help:{
      dn:"Tempo (ms) que a SOL 2 (nozzle) fica acionada — recua o nozzle para alimentar a BB. Aumente se a arma estiver falhando alimentação. Padrão 18 ms.",
      dr:"Em D8PA: espera entre DN e DP, dá tempo da mola empurrar o bico e vedar o bucking. Em S8PA: descanso entre tiros. Padrão 26 ms (D8PA) / 20 ms (S8PA).",
      dp:"Tempo (ms) que a SOL 1 (poppet) fica aberta — quanto maior, mais ar passa pelo cano. Aumente para canos longos ou BBs pesadas. Padrão 25 ms.",
      db:"Debounce do gatilho em unidades de 0,1 ms (1 unidade = 100 µs). Pausa antes do próximo ciclo, esperando a BB sair do cano. Só D8PA. Faixa 5–150 (0,5–15 ms). Padrão 5.",
      is:"Tempo (segundos) sem disparar até armar o boost antiaderência. Quando passar esse tempo parado, o próximo tiro recebe DP+IP. iP=0 desativa o boost.",
      ip:"Multiplicador do DP só no primeiro tiro depois do iS expirar. IP=1 → tiro com 2×DP, IP=2 → 3×DP, etc. Quebra a aderência do o-ring do poppet. Aumente até o primeiro tiro sair com o FPS normal.",
      rof:"Limite de cadência em tiros por segundo (rps). 0 = sem limite (cadência só pelos timings).",
      semiRof:"Tempo mínimo (ms) entre tiros em SEMI. Impede auto-disparo acidental com gatilhos rápidos. 0 = desativado.",
      rofTheo:"Cadência teórica em rps calculada a partir dos timings: 1000 ÷ (soma dos delays).",
      pos:"Modo de fogo quando o seletor está nesta posição.",
      sel3:"Habilita uma terceira posição do seletor. Requer sensor Hall (a opção de 3 stops digital não existe). Ao ligar, o seletor passa automaticamente para Hall.",
      trigMode:"Tipo do sensor do gatilho: microswitch digital ou Hall analógico.",
      selMode:"Tipo do sensor do seletor: microswitch digital ou Hall analógico. Hall é obrigatório se 3-pos estiver ativo. Quando Hall, a seção de calibração do seletor aparece.",
      mosSwap:"Se você soldou nozzle e poppet nos pinos trocados, marque para corrigir via software (D8PA).",
      silent:"Não toca confirmação do buzzer durante o uso normal.",
      sens:"Puxe o gatilho até o ponto onde quer disparar e clique Salvar — o ADC vira o ponto de disparo.",
      noise:"Faz 1 disparo completo medindo o ruído elétrico no Hall. Use ANTES de calibrar gatilho para definir a margem da deadband.",
      cal:"Captura os valores ADC do gatilho/seletor solto e pressionado.",
      mosTest:"Pulsa o MOSFET por 2 segundos. Use só para conferir a fiação — sem gas/munição.",
      trigTest:"Acende o indicador enquanto você puxa o gatilho. Não dispara solenoide. Auto-encerra após 15s sem atividade.",
      buzz:"Toca um padrão de aviso. Útil para testar o buzzer.",
      pwd:"Senha do AP WiFi. Mínimo 8 caracteres.",
      cfgLock:"Quando ativo e trancado, salvar slots e trocar de slot via web ficam bloqueados até você destrancar com a senha. Se esquecer a senha, segure o gatilho por 30 s no boot para reset de fábrica."
    }
  },
  en:{
    slotName:"Slot name",
    solSec:"Engine",
    solSHead:"Single Solenoid S8PA",solDHead:"Dual Solenoid D8PA",
    solS:"1 solenoid (Jack, Backdraft)",solD:"2 solenoids (F2, Pulsar)",
    timSec:"Timings",rofLbl:"ROF cap (rps)",rofTheoLbl:"Theoretical ROF",semiRof:"Semi Max ROF (ms)",
    selSec:"Selector",pos1:"Position 1",pos2:"Position 2",pos3:"Position 3",
    sel3:"3-position selector",sel3H:"enable Pos 3 (auto-Hall)",
    funcSec:"Functions",advSec:"Advanced",
    statsSec:"Statistics",statBattLbl:"Battery",statShotsSession:"Session shots",statShotsTotal:"Total shots",statLube:"Next lubrication",
    cfgLock:"Config LOCK",cfgLockOff:"OFF (no password)",cfgLockOnUnlocked:"ON — unlocked",
    cfgLockSetLbl:"New password",cfgLockSet:"Set",cfgLockLock:"Lock now",cfgLockClear:"Clear password",
    cfgLockTooShort:"Password too short (min 4)",cfgLockOk:"Password saved",cfgLockCleared:"Password cleared",
    cfgLockUnlocked:"Unlocked",cfgLockBadPwd:"Wrong password",
    cfgLockClearConfirm:"Clear the Config LOCK password?",
    lockTitle:"Configuration locked",lockMsg:"Enter the password to unlock the FCU configuration.",
    lockPwd:"Password",lockUnlock:"Unlock",
    lockForgotHint:"Forgot the password? Hold the trigger at boot for 30 s to factory-reset.",
    trigIn:"Trigger",selIn:"Selector type",sw:"Microswitch",hl:"Hall (analog)",
    invTrig:"Invert trigger",
    mosSwap:"Swap MOS 1 ↔ 2",mosSwapH:"fix swapped wiring",
    silent:"Silent mode",silentH:"skip buzzer while in use",
    sensSec:"Trigger sensitivity",sensHelp:"Pull trigger to the desired fire point and click Save.",
    curPoint:"Current point",savePoint:"Save point",liveAdc:"ADC reading",
    calTrigSec:"Trigger calibration",calTrigHelp:"Start with noise (fires 1 test cycle). Don't pull the trigger.",
    calSelSec:"Selector calibration",calSelHelp:"Start with noise (fires 1 test cycle). Don't touch the selector.",
    calNoise:"Noise",calTrig:"Trigger",calSel:"Selector (3 pos)",calBtn:"Calibrate",
    diagSec:"Diagnostics",buzz:"Buzzer",bzMode:"Mode change",bzSave:"Save OK",bzWifi:"WiFi ON",bzLow:"Low battery",bzCut:"Battery CUT",bzTest:"Test",play:"Play",mosTest:"MOSFET test (2s)",
    off:"off",
    trigTest:"Trigger test",trigTestStart:"Start",trigTestStop:"Stop",trigTestIdle:"—",trigTestDone:"test ended",
    wifiSec:"WiFi",newPwd:"New password",changePwd:"Change password",
    reload:"Reload",save:"Save slot",resetSlot:"Reset slot",cancel:"Cancel",capture:"Capture",saveCal:"Save",
    fSafe:"SAFE",fSemi:"SEMI",fFull:"FULL",fB2:"Burst 2",fB3:"Burst 3",fB4:"Burst 4",
    saved:"Slot saved",saveFail:"Save failed",reloaded:"Reloaded",resetOk:"Slot reset",
    resetConfirm:"Reset this slot to default values?",
    pwdOk:"Password changed",pwdBad:"Password too short (min 8)",buzzed:"Buzzer ✓",
    mosOk:"MOSFET pulsing 2s",mosFail:"Could not start",
    pointSaved:"Point saved: ADC ",
    noiseRunning:"Firing test cycle…",noiseOk:"Noise captured: ±",
    calStep1:"Fully release the trigger and click Capture.",
    calStep2:"Press trigger fully and click Capture.",
    calStep3:"Captured. Click Save to write.",
    calStepSel:"Move selector to position",
    calRangeErr:"Travel too short — retry.",
    help:{
      dn:"Time (ms) SOL 2 (nozzle) is energized — pulls back the nozzle to feed a BB. Increase if feeding fails. Default 18 ms.",
      dr:"In D8PA: wait between DN and DP for the spring to seal the bucking. In S8PA: inter-shot rest. Default 26 ms (D8PA) / 20 ms (S8PA).",
      dp:"Time (ms) SOL 1 (poppet) stays open — longer = more air through the barrel. Increase for long barrels or heavy BBs. Default 25 ms.",
      db:"Trigger debounce in units of 0.1 ms (1 unit = 100 µs). Pause before the next cycle, waiting for the BB to exit the barrel. D8PA only. Range 5–150 (0.5–15 ms). Default 5.",
      is:"Idle time (seconds) before arming the anti-stiction boost. After this much idle, the next shot fires with DP+IP. Set IP=0 to disable.",
      ip:"DP multiplier applied only to the first shot after IS expires. IP=1 → shot fires at 2×DP, IP=2 → 3×DP, etc. Breaks the poppet o-ring stiction. Raise it until the first shot reaches normal FPS.",
      rof:"Rate cap in rounds per second (rps). 0 = unlimited (cadence ruled by timings only).",
      semiRof:"Minimum time (ms) between SEMI shots. Blocks accidental double-taps from fast triggers. 0 = disabled.",
      rofTheo:"Theoretical cadence in rps from timings: 1000 ÷ (sum of delays).",
      pos:"Fire mode when the selector is in this position.",
      sel3:"Enables a third selector position. Requires Hall sensor (no 3-stop digital). Toggling on auto-switches the selector input to Hall.",
      trigMode:"Trigger sensor type: digital microswitch or analog Hall.",
      selMode:"Selector sensor type: digital microswitch or analog Hall. Hall is required when 3-pos is enabled. When Hall, the selector calibration section appears.",
      mosSwap:"If you soldered nozzle/poppet to the wrong pins, check this to fix in software (D8PA).",
      silent:"Skips buzzer confirmations during normal use.",
      sens:"Pull trigger to the point where you want it to fire and click Save — that ADC becomes the fire point.",
      noise:"Fires 1 full cycle while sampling the Hall ADC. Run BEFORE calibrating the trigger to set the deadband margin.",
      cal:"Captures ADC values for released/pressed trigger or each selector position.",
      mosTest:"Pulses the MOSFET for 2 seconds. Use only to check wiring — no gas/ammo.",
      trigTest:"Lights the indicator while you pull the trigger. Does not fire any solenoid. Auto-stops after 15s idle.",
      buzz:"Plays a warning pattern. Useful to test the buzzer.",
      pwd:"WiFi AP password. Minimum 8 characters.",
      cfgLock:"When active and locked, slot save/switch/reset via web are blocked until you unlock with the password. If you forget the password, hold the trigger at boot for 30 s to factory-reset."
    }
  }
};
let lang = "en";
let cur = { i:0, slot:null, meta:null };
let noiseMargin    = 0;
let noiseMarginSel = 0;
let openHelp = null;
let sensPollT = null;

function $(id){ return document.getElementById(id); }
function show(el, on){ if(!el) return; el.classList.toggle("hide", !on); }

async function jget(url){
  const r = await fetch(url, {cache:"no-store"});
  return r.json();
}
async function jpost(url, body){
  const r = await fetch(url, {method:"POST", headers:{"content-type":"application/json"}, body: JSON.stringify(body||{})});
  return r.json();
}

function toast(msg, isErr){
  const t = $("toast"); t.textContent = msg;
  t.classList.toggle("err", !!isErr);
  t.classList.add("show");
  clearTimeout(toast._t);
  toast._t = setTimeout(()=>t.classList.remove("show"), 2000);
}

function applyLang(){
  document.querySelectorAll("[data-i]").forEach(el=>{
    const k = el.getAttribute("data-i");
    if (I[lang][k]!=null && typeof I[lang][k] === "string") el.textContent = I[lang][k];
  });
  $("langBR").classList.toggle("on", lang==="br");
  $("langEN").classList.toggle("on", lang==="en");
  fillModeOpts($("selPos1"));
  fillModeOpts($("selPos2"));
  fillModeOpts($("selPos3"));
  if (cur.slot) {
    $("selPos1").value = cur.slot.selPos1;
    $("selPos2").value = cur.slot.selPos2;
    $("selPos3").value = cur.slot.selPos3;
  }
  recalcRofTheo();
  refreshStepperUi();
}

function fillModeOpts(sel){
  while (sel.firstChild) sel.removeChild(sel.firstChild);
  const opts = [
    ["0", I[lang].fSafe],
    ["1", I[lang].fSemi],
    ["2", I[lang].fFull],
    ["3", I[lang].fB2],
    ["4", I[lang].fB3],
    ["5", I[lang].fB4]
  ];
  for (const [v,t] of opts){
    const o = document.createElement("option");
    o.value = v; o.textContent = t;
    sel.appendChild(o);
  }
}

function fillSlotPicker(n, last){
  const sp = $("slotPick");
  while (sp.firstChild) sp.removeChild(sp.firstChild);
  for (let i=0;i<n;i++){
    const b = document.createElement("button");
    b.type = "button";
    b.className = "slot-btn"+(i===last?" on":"");
    b.textContent = String(i+1);
    b.dataset.idx = String(i);
    b.addEventListener("click", async ()=>{
      const idx = parseInt(b.dataset.idx,10);
      await loadSlot(idx);
      await jpost("/setslot?i="+idx, {});
      cur.meta.lastSlot = idx;
      Array.from(sp.children).forEach(c=>c.classList.remove("on"));
      b.classList.add("on");
      updateHeader();
    });
    sp.appendChild(b);
  }
}

function classifyBatt(b){
  if (!b) return null;
  if (b.cut) return "cut";
  if (b.low) return "err";
  const cells = b.cells|0;
  if (cells <= 0) return null;
  const perCell = (b.mv|0) / cells;
  if (perCell >= 3700) return "ok";
  if (perCell >= 3500) return "warn";
  return "err";
}

function formatBattText(b){
  if (!b) return "—";
  const mv = b.mv|0;
  const cells = b.cells|0;
  let txt = (mv/1000).toFixed(2)+"V";
  if (cells) txt += " ("+cells+"S)";
  if (b.cut) txt += " CUT";
  return txt;
}

function updateBatteryChip(){
  const chip = $("battChip");
  if (!chip) return;
  if (!cur.meta || !cur.meta.batt){
    show(chip, false);
    return;
  }
  show(chip, true);
  const b = cur.meta.batt;
  chip.classList.remove("ok","warn","err","cut");
  const cls = classifyBatt(b);
  if (b.cut) chip.classList.add("cut");
  if (cls) chip.classList.add(cls);
  $("battTxt").textContent = formatBattText(b);
}

function updateLockUi(){
  if (!cur.meta) return;
  const lk = cur.meta.cfgLock || {hasPwd:false, locked:false};
  const status   = $("cfgLockStatus");
  const rowSet   = $("rowCfgLockSet");
  const rowMng   = $("rowCfgLockManage");
  const overlay  = $("lockOver");
  if (overlay) show(overlay, !!lk.locked);
  if (status){
    status.textContent = lk.hasPwd ? I[lang].cfgLockOnUnlocked : I[lang].cfgLockOff;
  }
  if (rowSet) show(rowSet, !lk.hasPwd);
  if (rowMng) show(rowMng, !!lk.hasPwd);
}

function updateStats(){
  if (!cur.meta) return;
  const total   = (cur.meta.shotsTotal   != null ? cur.meta.shotsTotal   : (cur.meta.shots|0)) | 0;
  const session = (cur.meta.shotsSession != null ? cur.meta.shotsSession : 0) | 0;

  const sV = $("statShotsSessionVal"); if (sV) sV.textContent = session.toLocaleString();
  const tV = $("statShotsTotalVal");   if (tV) tV.textContent = total.toLocaleString();

  const lubeFill = $("lubeFill");
  const lubeTxt  = $("lubeTxt");
  if (lubeFill && lubeTxt){
    const interval = 10000;
    const into = total % interval;
    const pct = (into / interval) * 100;
    lubeFill.style.width = Math.min(100, pct).toFixed(1) + "%";
    lubeFill.classList.remove("warn","due");
    if (pct >= 95)      lubeFill.classList.add("due");
    else if (pct >= 80) lubeFill.classList.add("warn");
    lubeTxt.textContent = into.toLocaleString() + " / " + interval.toLocaleString();
  }

  const battStat = $("statBatt");
  const battVal  = $("statBattVal");
  if (battStat && battVal){
    if (cur.meta.batt){
      show(battStat, true);
      battVal.classList.remove("ok","warn","err","cut");
      const cls = classifyBatt(cur.meta.batt);
      if (cur.meta.batt.cut) battVal.classList.add("cut");
      if (cls) battVal.classList.add(cls);
      battVal.textContent = formatBattText(cur.meta.batt);
    } else {
      show(battStat, false);
    }
  }
}

function updateHeader(){
  if (!cur.meta) return;
  const variant = cur.meta.variant || (IS_PRO ? "—" : "Starter");
  const ssid = cur.meta.ssid || ("BCGA_FCU_" + (IS_PRO ? "PRO" : "STR"));
  const sol = (cur.slot && cur.slot.solenoids===1) ? "S8PA" : "D8PA";
  $("hdrName").textContent = ssid.replace(/_/g," ");
  $("hdrSub").textContent = "FCU "+variant+" • "+sol;
  $("ftVer").textContent = "v"+(cur.meta.fw||"");
  $("ftVar").textContent = variant;
  if (IS_PRO) updateBatteryChip();
  updateStats();
  updateLockUi();
}

function recalcRofTheo(){
  if (!cur.slot) { $("rofTheoVal").textContent = "— rps"; return; }
  const ms = (k)=> Math.max(2, Math.min(80, parseInt($(k+"N").value||"0",10)));
  const dbMs = ()=> Math.max(0.5, Math.min(15, (parseInt($("dbN").value||"0",10) || 0) / 10));
  const isS = cur.slot.solenoids === 1;
  const sum = isS ? (ms("dp") + ms("dr"))
                  : (ms("dn") + ms("dr") + ms("dp") + dbMs());
  if (!sum) { $("rofTheoVal").textContent = "— rps"; return; }
  const rps = 1000 / sum;
  $("rofTheoVal").textContent = rps.toFixed(1) + " rps";
}

function refreshSolenoidUI(){
  if (!cur.slot) return;
  const isS = cur.slot.solenoids===1;
  $("solS").classList.toggle("on", isS);
  $("solD").classList.toggle("on", !isS);
  show($("rowDn"), !isS);
  show($("rowDl"), !isS);
  show($("mos2Btn"), !isS);
  show($("rowMosSwap"), !isS);
  recalcRofTheo();
  updateHeader();
}

function refreshSelectorUI(){
  if (!cur.slot) return;
  if (cur.slot.sel3pos) cur.slot.selMode = 1;       // 3-pos always implies Hall
  $("sel3pos").checked = !!cur.slot.sel3pos;
  show($("rowPos3"), !!cur.slot.sel3pos);
  const selModeEl = $("selMode");
  if (selModeEl){
    selModeEl.value = cur.slot.selMode;
    // Lock the dropdown to Hall when 3-pos is active — switching back would
    // make the third position unreachable on a digital switch.
    selModeEl.disabled = !!cur.slot.sel3pos;
  }
  refreshCalUI();
}

function refreshCalUI(){
  if (!cur.slot) return;
  const trigHall = cur.slot.trigMode===1;
  const selHall  = cur.slot.selMode===1;
  show($("secCalTrig"), trigHall);
  show($("secCalSel"),  selHall);
  show($("secSens"),    trigHall);
  $("calTrigVals").textContent = "low="+cur.slot.hallTrigLow+" high="+cur.slot.hallTrigHigh;
  $("calSelVals").textContent  = "low1="+cur.slot.hallSelLow1+" low2="+cur.slot.hallSelLow2;
  $("curPoint").textContent = cur.slot.hallTrigHigh;
  if (trigHall) startSensPoll(); else stopSensPoll();
}

function applySlotToUi(s){
  cur.slot = s;
  $("slotName").value = s.name||"";
  fillModeOpts($("selPos1"));
  fillModeOpts($("selPos2"));
  fillModeOpts($("selPos3"));
  $("selPos1").value = s.selPos1;
  $("selPos2").value = s.selPos2;
  $("selPos3").value = s.selPos3;
  $("trigMode").value  = s.trigMode;
  $("sel3pos").checked = !!s.sel3pos;
  $("mosfetSwap").checked = !!s.mosfetSwap;
  $("invertTrig").checked = !!s.invertTrig;
  $("silent").checked     = !!s.silent;
  for (const k of ["dn","dr","dp","db"]){
    $(k+"R").value = s[k]; $(k+"N").value = s[k];
  }
  $("rofN").value = s.rof;
  $("semiRofN").value = s.semiRofMs || 0;
  refreshStepperUi();
  refreshSolenoidUI();
  refreshSelectorUI();
}

async function loadMeta(){
  cur.meta = await jget("/load");
  if (cur.meta.lang) lang = (cur.meta.lang==="br") ? "br" : "en";
  fillSlotPicker(cur.meta.slots|0, cur.meta.lastSlot|0);
  cur.i = cur.meta.lastSlot|0;
  applyLang();
  updateHeader();
}

async function loadSlot(i){
  const r = await jget("/getslot?i="+i);
  if (!r.ok) { toast("ERR "+(r.error||""), true); return; }
  cur.i = i;
  applySlotToUi(r.slot);
}

function readSlotFromUi(){
  const pair = (k)=> Math.max(2, Math.min(80, parseInt($(k+"N").value||"0",10)));
  const dbUnits = ()=> Math.max(5, Math.min(150, parseInt($("dbN").value||"0",10)));
  return {
    name: $("slotName").value || ("Slot "+(cur.i+1)),
    solenoids: $("solD").classList.contains("on") ? 2 : 1,
    trigMode: parseInt($("trigMode").value,10),
    selMode:  cur.slot.selMode,
    sel3pos:  $("sel3pos").checked,
    selPos1:  parseInt($("selPos1").value,10),
    selPos2:  parseInt($("selPos2").value,10),
    selPos3:  parseInt($("selPos3").value,10),
    dn: pair("dn"), dr: pair("dr"), dp: pair("dp"), db: dbUnits(),
    rof:   Math.max(0, Math.min(50, parseInt($("rofN").value||"0",10))),
    semiRofMs: Math.max(0, Math.min(500, parseInt($("semiRofN").value||"0",10))),
    is: Math.max(0, Math.min(600, (cur.slot && cur.slot.is|0) || 0)),
    ip: Math.max(0, Math.min(5,   (cur.slot && cur.slot.ip|0) || 0)),
    hallTrigLow:  cur.slot.hallTrigLow,
    hallTrigHigh: cur.slot.hallTrigHigh,
    hallSelLow1:  cur.slot.hallSelLow1,
    hallSelLow2:  cur.slot.hallSelLow2,
    mosfetSwap: $("mosfetSwap").checked,
    invertTrig: $("invertTrig").checked,
    silent:     $("silent").checked,
    makeActive: true
  };
}

async function saveSlot(){
  const body = readSlotFromUi();
  const r = await jpost("/save?i="+cur.i, body);
  if (r.ok) { toast(I[lang].saved); cur.slot = body; updateHeader(); }
  else toast(I[lang].saveFail+": "+(r.error||""), true);
}

async function resetSlot(){
  if (!confirm(I[lang].resetConfirm)) return;
  const r = await jpost("/reset?i="+cur.i, {});
  if (r.ok && r.slot) {
    applySlotToUi(r.slot);
    toast(I[lang].resetOk);
  } else {
    toast(I[lang].saveFail+": "+(r.error||""), true);
  }
}

function bindPair(k){
  const r = $(k+"R"), n = $(k+"N");
  const sync = (src, dst) => {
    dst.value = src.value;
    if (cur.slot) cur.slot[k] = parseInt(src.value || "0", 10);
    recalcRofTheo();
    // IP display depends on the current DP value, so refresh the stepper too.
    if (k === "dp") refreshStepper("ip");
  };
  r.addEventListener("input", ()=> sync(r, n));
  n.addEventListener("input", ()=> sync(n, r));
}

const STEPPERS = {
  is: { step: 5, min: 0, max: 600, fmt: v => v === 0 ? I[lang].off : v + " s" },
  ip: {
    step: 1, min: 0, max: 5,
    // IP is a multiplier on DP — show count and the resulting boost (in ms)
    // computed from whatever DP the user has dialled in.
    fmt: v => {
      if (v === 0) return I[lang].off;
      const dp = (cur.slot && cur.slot.dp) ? (cur.slot.dp|0) : 0;
      return v + "× (+" + (v * dp) + " ms)";
    }
  }
};

function refreshStepper(k){
  const cfg = STEPPERS[k];
  const valEl = $(k+"Val");
  if (!valEl) return;
  const v = (cur.slot && cur.slot[k] != null) ? (cur.slot[k]|0) : cfg.min;
  valEl.textContent = cfg.fmt(v);
  valEl.classList.toggle("off", v === 0);
}

function refreshStepperUi(){
  for (const k of Object.keys(STEPPERS)) refreshStepper(k);
}

function bindStepper(k){
  const cfg = STEPPERS[k];
  document.querySelectorAll('[data-step="'+k+'"]').forEach(btn=>{
    btn.addEventListener("click", ()=>{
      if (!cur.slot) return;
      const dir = parseInt(btn.dataset.dir, 10);
      const cur_v = (cur.slot[k]|0);
      const nv = Math.max(cfg.min, Math.min(cfg.max, cur_v + dir * cfg.step));
      cur.slot[k] = nv;
      refreshStepper(k);
    });
  });
}

function closeHelp(){
  if (openHelp){ openHelp.remove(); openHelp = null; }
}
function openHelpFor(btn){
  closeHelp();
  const k = btn.dataset.h;
  const txt = (I[lang].help && I[lang].help[k]) || k;
  const pop = document.createElement("div");
  pop.className = "popover";
  pop.textContent = txt;
  document.body.appendChild(pop);
  const r = btn.getBoundingClientRect();
  let left = r.left + window.scrollX;
  let top  = r.bottom + window.scrollY + 6;
  pop.style.left = "0px"; pop.style.top = "0px";
  const w = pop.offsetWidth;
  const maxLeft = window.scrollX + document.documentElement.clientWidth - w - 8;
  if (left > maxLeft) left = maxLeft;
  if (left < 8) left = 8;
  pop.style.left = left+"px";
  pop.style.top  = top+"px";
  openHelp = pop;
}
document.addEventListener("click", (e)=>{
  const t = e.target;
  if (t && t.classList && t.classList.contains("help")){
    e.stopPropagation();
    if (openHelp && openHelp._anchor === t){ closeHelp(); return; }
    openHelpFor(t);
    if (openHelp) openHelp._anchor = t;
    return;
  }
  if (openHelp && !openHelp.contains(t)) closeHelp();
});

function startSensPoll(){
  stopSensPoll();
  sensPollT = setInterval(async ()=>{
    if ($("secSens").classList.contains("hide")) return;
    try {
      const r = await jget("/halllive?ch=t");
      if (r.ok) $("sensLive").textContent = r.value;
    } catch(e){}
  }, 300);
}
function stopSensPoll(){ if (sensPollT){ clearInterval(sensPollT); sensPollT=null; } }

async function saveSensitivity(){
  try {
    const r = await jget("/halllive?ch=t");
    if (!r.ok) { toast("ERR", true); return; }
    const v = r.value|0;
    cur.slot.hallTrigHigh = v;
    if (cur.slot.hallTrigLow >= v - 20) cur.slot.hallTrigLow = Math.max(0, v - 200);
    const sv = await jpost("/save?i="+cur.i, {
      hallTrigHigh: cur.slot.hallTrigHigh,
      hallTrigLow:  cur.slot.hallTrigLow
    });
    if (sv.ok) { toast(I[lang].pointSaved + v); refreshCalUI(); }
    else toast(I[lang].saveFail, true);
  } catch(e) { toast(String(e), true); }
}

let calMode = null;
let calStep = 0;
let calBuf  = [];
let livePollT = null;

function startLivePoll(ch){
  stopLivePoll();
  livePollT = setInterval(async ()=>{
    try {
      const r = await jget("/halllive?ch="+ch);
      if (r.ok) $("liveVal").textContent = r.value;
    } catch(e){}
  }, 250);
}
function stopLivePoll(){ if (livePollT){ clearInterval(livePollT); livePollT=null; } }

function setStepDots(active, total){
  total = total || 3;
  $("step1").classList.toggle("on", active>=1);
  $("step2").classList.toggle("on", active>=2 && total>=2);
  $("step3").classList.toggle("on", active>=3 && total>=3);
  show($("step2"), total>=2);
  show($("step3"), total>=3);
}

function calClose(){ stopLivePoll(); show($("calOver"), false); calMode=null; }

function calOpenNoise(target){
  calMode = (target === "s") ? "selNoise" : "trigNoise";
  calStep = 1;
  const sec = (target === "s") ? I[lang].calSelSec : I[lang].calTrigSec;
  $("calTitle").textContent = I[lang].calNoise + " — " + sec;
  $("calMsg").textContent = I[lang].help.noise;
  $("calNext").textContent = I[lang].calBtn;
  $("liveVal").textContent = "—";
  setStepDots(1, 1);
  show($("calOver"), true);
}

function calOpenTrig(){
  calMode = "trig"; calStep = 1; calBuf = [];
  $("calTitle").textContent = I[lang].calTrig + " — " + I[lang].calTrigSec;
  $("calMsg").textContent = I[lang].calStep1;
  $("calNext").textContent = I[lang].capture;
  setStepDots(1, 3);
  show($("calOver"), true);
  startLivePoll("t");
}

function calOpenSel(){
  calMode = "sel"; calStep = 1; calBuf = [];
  $("calTitle").textContent = I[lang].calSel + " — " + I[lang].calSelSec;
  $("calMsg").textContent = I[lang].calStepSel + " 1.";
  $("calNext").textContent = I[lang].capture;
  setStepDots(1, 3);
  show($("calOver"), true);
  startLivePoll("s");
}

async function calNextNoise(){
  const isSel = (calMode === "selNoise");
  const ch    = isSel ? "s" : "t";
  $("calMsg").textContent = I[lang].noiseRunning;
  $("calNext").disabled = true;
  try {
    const r = await jpost("/noisecal", {ch:ch});
    if (r.ok) {
      const m = r.margin|0;
      if (isSel) {
        noiseMarginSel = m;
        $("calSelNoiseVals").textContent = "± " + m;
      } else {
        noiseMargin = m;
        $("calTrigNoiseVals").textContent = "± " + m;
      }
      $("calMsg").textContent = I[lang].noiseOk + m;
      $("calNext").textContent = I[lang].cancel;
      $("calNext").onclick = calClose;
    } else {
      toast(r.error||"err", true);
    }
  } catch(e){ toast(String(e), true); }
  finally { $("calNext").disabled = false; }
}

function calNextTrig(){
  const v = parseInt($("liveVal").textContent||"0",10);
  if (calStep===1){
    calBuf[0] = v;
    calStep = 2;
    setStepDots(2, 3);
    $("calMsg").textContent = I[lang].calStep2;
  } else if (calStep===2){
    calBuf[1] = v;
    calStep = 3;
    setStepDots(3, 3);
    let lo = Math.min(calBuf[0], calBuf[1]);
    let hi = Math.max(calBuf[0], calBuf[1]);
    const margin = Math.max(noiseMargin, 50);
    let lo2 = lo + margin;
    let hi2 = hi - margin;
    if (lo2 >= hi2) {
      $("calMsg").textContent = I[lang].calRangeErr;
      return;
    }
    cur.slot.hallTrigLow  = lo2;
    cur.slot.hallTrigHigh = hi2;
    $("calMsg").textContent = I[lang].calStep3 + " (low="+lo2+" high="+hi2+")";
    $("calNext").textContent = I[lang].saveCal;
  } else {
    jpost("/save?i="+cur.i, {hallTrigLow:cur.slot.hallTrigLow, hallTrigHigh:cur.slot.hallTrigHigh})
      .then(r=>{ toast(r.ok?I[lang].saved:I[lang].saveFail, !r.ok); refreshCalUI(); calClose(); });
  }
}

function calNextSel(){
  const v = parseInt($("liveVal").textContent||"0",10);
  if (calStep <= 3){
    calBuf[calStep-1] = v;
    calStep++;
    if (calStep <= 3){
      setStepDots(calStep, 3);
      $("calMsg").textContent = I[lang].calStepSel + " " + calStep + ".";
      return;
    }
    const sorted = calBuf.slice(0,3).sort((a,b)=>a-b);
    cur.slot.hallSelLow1 = Math.round((sorted[0]+sorted[1])/2);
    cur.slot.hallSelLow2 = Math.round((sorted[1]+sorted[2])/2);
    $("calMsg").textContent = I[lang].calStep3 + " (low1="+cur.slot.hallSelLow1+" low2="+cur.slot.hallSelLow2+")";
    $("calNext").textContent = I[lang].saveCal;
  } else {
    jpost("/save?i="+cur.i, {
      hallSelLow1: cur.slot.hallSelLow1,
      hallSelLow2: cur.slot.hallSelLow2
    }).then(r=>{ toast(r.ok?I[lang].saved:I[lang].saveFail, !r.ok); refreshCalUI(); calClose(); });
  }
}

function calNext(){
  if (calMode === "trigNoise" || calMode === "selNoise") return calNextNoise();
  if (calMode === "trig") return calNextTrig();
  if (calMode === "sel")  return calNextSel();
}

let trigTestT = null;
let trigTestLastEvt = 0;
let trigTestLastActivity = 0;
function trigTestStop(){
  if (trigTestT){ clearInterval(trigTestT); trigTestT = null; }
  $("trigTestBtn").textContent = I[lang].trigTestStart;
  $("trigTestDot").classList.remove("on");
  $("trigTestMsg").textContent = I[lang].trigTestDone;
}
function trigTestStart(){
  if (trigTestT) return;
  trigTestLastEvt = 0;
  trigTestLastActivity = Date.now();
  $("trigTestBtn").textContent = I[lang].trigTestStop;
  $("trigTestMsg").textContent = "…";
  trigTestT = setInterval(async ()=>{
    try {
      const r = await jget("/trigstate");
      if (!r.ok) return;
      $("trigTestDot").classList.toggle("on", !!r.pressed);
      if (r.events !== trigTestLastEvt){
        trigTestLastEvt = r.events;
        trigTestLastActivity = Date.now();
      }
      if (Date.now() - trigTestLastActivity > 15000){
        trigTestStop();
      }
    } catch(e){}
  }, 150);
}

window.addEventListener("DOMContentLoaded", async ()=>{
  ["dn","dr","dp","db"].forEach(bindPair);
  ["is","ip"].forEach(bindStepper);

  $("langBR").addEventListener("click", ()=>{ lang="br"; jpost("/setlang",{lang:"br"}); applyLang(); refreshSelectorUI(); });
  $("langEN").addEventListener("click", ()=>{ lang="en"; jpost("/setlang",{lang:"en"}); applyLang(); refreshSelectorUI(); });

  $("solS").addEventListener("click", ()=>{ if(!cur.slot) return; cur.slot.solenoids=1; refreshSolenoidUI(); });
  $("solD").addEventListener("click", ()=>{ if(!cur.slot) return; cur.slot.solenoids=2; refreshSolenoidUI(); });

  $("trigMode").addEventListener("change", e=>{ if(!cur.slot) return; cur.slot.trigMode = parseInt(e.target.value,10); refreshCalUI(); });
  $("selMode").addEventListener("change", e=>{
    if(!cur.slot) return;
    cur.slot.selMode = parseInt(e.target.value,10);
    refreshCalUI();
  });
  $("sel3pos").addEventListener("change", e=>{
    if(!cur.slot) return;
    cur.slot.sel3pos = e.target.checked ? 1 : 0;
    if (cur.slot.sel3pos) cur.slot.selMode = 1;
    refreshSelectorUI();
  });

  $("btnSave").addEventListener("click", saveSlot);
  $("btnReset").addEventListener("click", resetSlot);
  $("btnReload").addEventListener("click", async ()=>{ await loadMeta(); await loadSlot(cur.i); toast(I[lang].reloaded); });

  $("buzzPlay").addEventListener("click", async ()=>{
    const v = parseInt($("buzzPick").value,10);
    const r = await jpost("/test", {buzz:v});
    if (r.ok) toast(I[lang].buzzed);
  });
  $("mos1Btn").addEventListener("click", async ()=>{
    const r = await jpost("/test", {mos:1});
    toast(r.ok ? I[lang].mosOk : (I[lang].mosFail+": "+(r.error||"")), !r.ok);
  });
  $("mos2Btn").addEventListener("click", async ()=>{
    const r = await jpost("/test", {mos:2});
    toast(r.ok ? I[lang].mosOk : (I[lang].mosFail+": "+(r.error||"")), !r.ok);
  });
  $("trigTestBtn").addEventListener("click", ()=>{
    if (trigTestT) trigTestStop(); else trigTestStart();
  });

  $("setPwdBtn").addEventListener("click", async ()=>{
    const p = $("wifiPwd").value || "";
    if (p.length < 8) { toast(I[lang].pwdBad, true); return; }
    const r = await jpost("/setpwd", {pwd:p});
    toast(r.ok ? I[lang].pwdOk : (r.error||"err"), !r.ok);
    if (r.ok) $("wifiPwd").value = "";
  });

  $("sensSaveBtn").addEventListener("click", saveSensitivity);

  $("cfgLockSetBtn").addEventListener("click", async ()=>{
    const pwd = $("cfgLockPwd").value || "";
    if (pwd.length < 4) { toast(I[lang].cfgLockTooShort, true); return; }
    const r = await jpost("/cfglock", {action:"set", pwd});
    if (r.ok){
      $("cfgLockPwd").value = "";
      cur.meta.cfgLock = {hasPwd:r.hasPwd, locked:r.locked};
      updateLockUi();
      toast(I[lang].cfgLockOk);
    } else toast(r.error||"err", true);
  });
  $("cfgLockLockBtn").addEventListener("click", async ()=>{
    const r = await jpost("/cfglock", {action:"lock"});
    if (r.ok){
      cur.meta.cfgLock = {hasPwd:r.hasPwd, locked:r.locked};
      updateLockUi();
    } else toast(r.error||"err", true);
  });
  $("cfgLockClearBtn").addEventListener("click", async ()=>{
    if (!confirm(I[lang].cfgLockClearConfirm)) return;
    const r = await jpost("/cfglock", {action:"clear"});
    if (r.ok){
      cur.meta.cfgLock = {hasPwd:r.hasPwd, locked:r.locked};
      updateLockUi();
      toast(I[lang].cfgLockCleared);
    } else toast(r.error||"err", true);
  });
  $("lockUnlockBtn").addEventListener("click", async ()=>{
    const pwd = $("lockPwdInput").value || "";
    const r = await jpost("/cfglock", {action:"unlock", pwd});
    if (r.ok && !r.locked){
      $("lockPwdInput").value = "";
      cur.meta.cfgLock = {hasPwd:r.hasPwd, locked:r.locked};
      updateLockUi();
      toast(I[lang].cfgLockUnlocked);
      try { await loadSlot(cur.i); } catch(e){}
    } else toast(I[lang].cfgLockBadPwd, true);
  });

  $("calTrigNoiseBtn").addEventListener("click", ()=>calOpenNoise("t"));
  $("calSelNoiseBtn").addEventListener("click",  ()=>calOpenNoise("s"));
  $("calTrigBtn").addEventListener("click", calOpenTrig);
  $("calSelBtn").addEventListener("click", calOpenSel);
  $("calCancel").addEventListener("click", calClose);
  $("calNext").addEventListener("click", ()=>{
    if (calNext._suppress) { calNext._suppress = false; return; }
    calNext();
  });

  await loadMeta();
  await loadSlot(cur.i);

  // Periodic /load poll keeps stats (shots, battery on PRO) live without a manual reload.
  // PRO refreshes at 5 s for tighter battery readout; STR can use 10 s since it only needs shots.
  const pollMs = IS_PRO ? 5000 : 10000;
  setInterval(async ()=>{ try { cur.meta = await jget("/load"); updateHeader(); } catch(e){} }, pollMs);
});
</script></body>
</html>
)HTML";
