#!/usr/bin/env python3
"""Build firmware/<variant>/web_ui.h from firmware/web_ui_dev/*.

Reads index_<variant>.html, inlines style.css into <style> and app.js into <script>,
strips <script src="mock.js">, wraps in a C++ raw string, and writes the result to
firmware/BCGA_FCU_<VARIANT>/web_ui.h.

Run with no args to rebuild both variants. Run with --variant=str|pro for one only.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEV_DIR = ROOT / "firmware" / "web_ui_dev"

HEADERS = {
    "str": """// BCGA FCU STR — web_ui.h
// Single-page dashboard served on GET /. Stored in PROGMEM as raw string.
// Starter (perfboard) variant: S8PA + D8PA. No battery chip, no WiFi button.
//
// Generated by tools/build_web_ui.py — DO NOT EDIT BY HAND.
// Edit firmware/web_ui_dev/{style.css, app.js, index_str.html} and rebuild.
//
// Section order:
//   - Header: gear logo, name, S8PA/D8PA tag, BR/EN (default EN)
//   - Slot picker: 3 buttons at the top
//   - Engine (slot name + Single/Dual radio cards)
//   - Timings (DN/DR/DP em ms) + ROF max + ROF teórico
//   - Seletor (Pos1/Pos2; toggle 3-pos auto-ativa Hall e revela Pos3)
//   - Funções (Sw/Hall do gatilho, swap MOS, silent — invertTrig hidden)
//   - Sensibilidade (só Hall trigger): captura de ponto único
//   - Calibração do gatilho (só Hall trigger): ruído + solto/pressionado
//   - Calibração do seletor (só Hall sel): ruído + 3 posições
//   - Avançado (IS/IP anti-stiction + DB em 0,1 ms + Semi Max ROF)
//   - Diagnóstico (buzzer + Test MOS — 2s, respeita mosfetSwap)
//   - WiFi (trocar senha)

#pragma once

#include <Arduino.h>

const char WEB_UI_HTML[] PROGMEM = R\"HTML(""",
    "pro": """// BCGA FCU PRO — web_ui.h
// Single-page dashboard served on GET /. Stored in PROGMEM as raw string.
//
// Generated by tools/build_web_ui.py — DO NOT EDIT BY HAND.
// Edit firmware/web_ui_dev/{style.css, app.js, index_pro.html} and rebuild.
//
// Section order:
//   - Header: gear logo, name, S8PA/D8PA tag, battery chip, BR/EN (default EN)
//   - Slot picker: 3 buttons at the top (always clickable)
//   - Engine (slot name + Single/Dual radio cards)
//   - Timings (DN/DR/DP em ms) + ROF max + ROF teórico
//   - Seletor (Pos1/Pos2; toggle 3-pos auto-ativa Hall e revela Pos3)
//   - Funções (Sw/Hall do gatilho, swap MOS, silent — invertTrig hidden)
//   - Sensibilidade (só Hall trigger): captura de ponto único
//   - Calibração do gatilho (só Hall trigger): ruído + solto/pressionado
//   - Calibração do seletor (só Hall sel): ruído + 3 posições
//   - Avançado (IS/IP anti-stiction + DB em 0,1 ms + Semi Max ROF)
//   - Diagnóstico (buzzer + Test MOS — 2s, respeita mosfetSwap)
//   - WiFi (trocar senha)
// Toolbar: Resetar slot · Recarregar · Salvar.
// Footer: link bcgaairsoft.com.br + versão + variante.

#pragma once

#include <Arduino.h>

const char WEB_UI_HTML[] PROGMEM = R\"HTML(""",
}

FOOTER = ")HTML\";\n"

LINK_RE = re.compile(r'<link\s+rel="stylesheet"\s+href="style\.css"\s*/?>\s*')
APP_SCRIPT_RE = re.compile(r'<script\s+src="app\.js"></script>\s*')
MOCK_SCRIPT_RE = re.compile(r'<script\s+src="mock\.js"></script>\s*')


def build_one(variant: str) -> Path:
    if variant not in HEADERS:
        raise ValueError(f"unknown variant {variant!r}")

    html_path = DEV_DIR / f"index_{variant}.html"
    css_path = DEV_DIR / "style.css"
    js_path = DEV_DIR / "app.js"
    for p in (html_path, css_path, js_path):
        if not p.is_file():
            raise FileNotFoundError(p)

    html = html_path.read_text(encoding="utf-8")
    css = css_path.read_text(encoding="utf-8").rstrip()
    js = js_path.read_text(encoding="utf-8").rstrip()

    if not LINK_RE.search(html):
        raise RuntimeError(f'{html_path} missing <link rel="stylesheet" href="style.css">')
    if not APP_SCRIPT_RE.search(html):
        raise RuntimeError(f'{html_path} missing <script src="app.js">')

    html = MOCK_SCRIPT_RE.sub("", html)
    html = LINK_RE.sub(f"<style>\n{css}\n</style>", html, count=1)
    html = APP_SCRIPT_RE.sub(f"<script>\n{js}\n</script>", html, count=1)

    if ')HTML"' in html:
        raise RuntimeError(
            f"{html_path}: content contains ')HTML\"' which collides with the C++ raw "
            "string delimiter. Change the offending text or pick another delimiter."
        )

    out = HEADERS[variant] + html.lstrip() + FOOTER
    out_path = ROOT / "firmware" / f"BCGA_FCU_{variant.upper()}" / "web_ui.h"
    out_path.write_text(out, encoding="utf-8", newline="\n")
    return out_path


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--variant", choices=("str", "pro", "all"), default="all")
    args = ap.parse_args(argv)

    targets = ("str", "pro") if args.variant == "all" else (args.variant,)
    for v in targets:
        out = build_one(v)
        size = out.stat().st_size
        print(f"  wrote {out.relative_to(ROOT)} ({size:,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
